### ISSUE TITLE
Question: Which ports does the WLL driver use?

### ISSUE THREAD

**Issue by paulober** [michael-slx/weewx-weatherlink-live#17]
Which ports should I open in ufw (My local firewall) for WLL weewx driver?

**Comment by michael-slx** [comment]
The WLL driver uses the following ports:

- **TCP `80`** (HTTP) outbound: for issuing requests to the WeatherLink Live
- **UDP `22222`** broadcasts inbound: for receiving the 2.5 second push updates

**Comment by paulober** [comment]
Ok, thanks

**Comment by paulober** [comment]
Do you know if weewx require any other ports than 80 and 443 (standard)?

**Comment by selectSt4r** [comment]
I don't believe so.  [There is a user group](https://groups.google.com/g/weewx-user/search?q=weatherlinklive) that I recommend you check out and bookmark.  I've prepopulated the search term for this repo's extension, but change the search to find answers for any other Q's you might have about weewx.

**Comment by paulober** [comment]
Thanks again
