### ISSUE TITLE
Barometric pressure is not plotted in weewx HTML pages

### ISSUE THREAD

**Issue by kanudude** [michael-slx/weewx-weatherlink-live#18]
To properly plot barometric pressure in weewx HTML template the following changes are needed in
static/targets.py

change from:
BARO_ABSOLUTE = ["pressure"] 

change to:
BARO_ABSOLUTE = ["barometer"]

**Comment by michael-slx** [comment]
To my knowledge, that would change semantics from "absolute pressure measured by the station" to "Sea Level Pressure" ([quoted from WeeWX documentation](http://www.weewx.com/docs/customizing.htm#genLoopPackets)).
Do you have any confirmation that the `bar_absolute` value returned by the WLL actually corresponds to the latter?

What is the issue with the plot?

**Comment by nickbp** [comment]
If it helps, I see both sea-level and absolute pressure when manually querying `/v1/current_conditions` on a weatherlink live that's getting data from a vantage vue:
```
      {
        "lsid": xxx,
        "data_structure_type": 3,
        "bar_sea_level": 30.36,
        "bar_trend": 0.062,
        "bar_absolute": 30.253
      }
```

**Comment by michael-slx** [comment]
I unfortunately cannot confirm the issue the OP has. The suggested "fix" would change semantics of the data.

_Closing this for now_
