### ISSUE TITLE
Driver crashes and WeeWx cannot recover

### ISSUE THREAD

**Issue by selectSt4r** [michael-slx/weewx-weatherlink-live#6]
See log.  I had WeeWx set to capture the log in debug detail.  The first few hundred lines show normal behavior.  The crash stack is toward the end.
[weewx weatherlink-live crashlog.txt](https://github.com/michael-slx/weewx-weatherlink-live/files/6177854/weewx.weatherlink-live.crashlog.txt)

**Comment by michael-slx** [comment]
I see you are using the Weather34 skin. Could you try to run WeeWX without the skin (at least with the services disabled), just to see if the issues still appear?

What Pi model are you using?

**Comment by selectSt4r** [comment]
Hi Michael -- I'm running it on a Pi 4 with Raspbian 10 Buster.  I will remove Weather34 and report back in a few days.  The crash sometimes takes a few days to happen.  It's happened a few times.

**Comment by selectSt4r** [comment]
Removing Weather34 seems to have resolved the issue.  What was your instinct about taking the skin out of the equation?

**Comment by michael-slx** [comment]
Your log shows that WeeWX could not start any more threads. The driver only starts 2 or so threads and always checks if the old ones have finished before starting new ones. I've checked this by profiling/debugging the driver for 2-3 hours.

So, I've guessed it was caused by Weather34.
